spring:
  application:
    name: "gateway-service"

server:
  port: 8081

jwt:
  secret: "incorrect"
  expire: 9999999

logging:
  file: 'logs/@project.artifactId@/log.log'
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n'
  level:
    root: info

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    logfile:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /statistic
      exposure:
        include: '*'

