host: arch.homework

ambassador:
  fullnameOverride: general-ambassador
  replicaCount: 1
  service:
    type: NodePort
    ports:
      - name: http
        port: 80
        targetPort: 8080
      - name: https
        port: 443
        targetPort: 8443
    externalTrafficPolicy:
  enableAES: true
  redis:
    create: true
  authService:
    create: true
  rateLimit:
    create: false

postgresql:  
  postgresqlUsername: rined
  postgresqlPassword: password
  postgresqlDatabase: otus_app
  service:
    port: "5432"

prometheus-operator:
  grafana:
    adminPassword: password
    notifiers:
      notifiers.yaml:
        notifiers:
          - name: Email
            type: email
            uid: notifier1           
            is_default: true
            send_reminder: false
            disable_resolve_message: false
            settings:
              addresses: example@example.example
              uploadImage: false              
    grafana.ini:
      smtp:
        enabled: true
        host: smtp.gmail.com:587
        from_address: 
        user: 
        password: 
        skip_verify: true
        from_name: Grafana
    service:
      type: NodePort
      nodePort: 30002
  prometheus:
    service:
      type: NodePort
      nodePort: 30001  
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      additionalScrapeConfigs:
        - job_name: pg-exporter
          scrape_interval: 1m
          static_configs:
          - targets: ['pg-exporter:80']
prometheus-postgres-exporter:
  config:
    datasource:
      host: pg-db
      user: rined
      password: password
      database: otus_app