replicaCount: 1
updateType: RollingUpdate
host: arch.homework
fullnameOverride: saga-service

image: rined/dms-saga:v3

service:
  type: NodePort
  port: 9999

postgresql:
  fullnameOverride: pg-db
  postgresqlUsername: rined
  postgresqlPassword: password
  postgresqlDatabase: otus_app
  service:
    port: "5432"