server:
  port: 8084
  error:
    include-message: always
  servlet:
    context-path: /api/v1

spring:
  data:
    mongodb:
      username: ${mongo.user}
      password: ${mongo.password}
      database: ${mongo.db}
      host: ${mongo.host}
      port: ${mongo.port}
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:general-kafka:9092}
    consumer:
      group-id: deal_consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      client-id: deal_service
    producer:
      client-id: deal_service
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 2
logging:
  file:
    name: 'logs/@project.artifactId@/log.log'
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n'
  level:
    root: info

hystrix:
  command:
    dealCreation:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500

management:
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles-histogram: true
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    logfile:
      enabled: true
    env:
      enabled: true
    deal-statistic:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /statistic
      exposure:
        include: '*'

info:
  app:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@