apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  PG_DB: {{ .Values.postgresql.postgresqlDatabase | quote }}
  PG_PORT: {{ .Values.postgresql.service.port | quote }}  
  PG_USER: {{ .Values.postgresql.postgresqlUsername | quote }}
  PG_HOST: {{ .Values.postgresql.fullnameOverride | quote }}
  
---

apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
type: Opaque
data:
  PG_PASSWORD: {{ .Values.postgresql.postgresqlPassword  | b64enc | quote }}    