apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-template.fullname" . }}
  labels:
    {{- include "service-template.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateType }}  
  selector:
    matchLabels:
      {{- include "service-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service-template.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}        
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: web
              containerPort: 8083
              protocol: TCP              
          env:
            - name: mongo.host
              valueFrom:
                configMapKeyRef:
                  name: template-config
                  key: MONGO_HOST  
            - name: mongo.port
              valueFrom:
                configMapKeyRef:
                  name: template-config
                  key: MONGO_PORT          
            - name: mongo.db
              valueFrom:
                configMapKeyRef:
                  name: template-config
                  key: MONGO_DB                
            - name: mongo.user
              valueFrom:
                configMapKeyRef:
                  name: template-config
                  key: MONGO_USER                  
            - name: mongo.password
              valueFrom:
                secretKeyRef:
                  name: template-secret
                  key: MONGO_PASSWORD                  
          livenessProbe:
              httpGet:
                port: web
                path: /api/v1/statistic/health
              initialDelaySeconds: 60
              periodSeconds: 15
          readinessProbe:
              httpGet:
                port: web
                path: /api/v1/statistic/health
              initialDelaySeconds: 5
              periodSeconds: 3   
