spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/state-machine
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false