apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-ui.fullname" . }}
  labels:
    {{- include "service-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateType }}  
  selector:
    matchLabels:
      {{- include "service-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service-ui.selectorLabels" . | nindent 8 }}               
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: web
              containerPort: 80
              protocol: TCP          