services:
  app:
    image: dms-proposal-img
    container_name: dms-proposal-container
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8082
    ports:
      - 8082:8082
    environment:
      - x_template_service_prefix=/template
      - x_template_service_port=80
      - x_template_service_host=arch.homework
      - spring_profiles_active=dev
      - mongo.db=dms-proposal
      - mongo.user=admin
      - mongo.password=admin
      - mongo.host=mongo-proposal-db
      - mongo.port=27017
    depends_on:
      - mongo-proposal-db
  mongo-proposal-db:
    image: mongo:latest
    container_name: dms-mogno-proposal-db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: dms-proposal
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin