server:
  port: 8080

spring:
  application:
    name: "gateway-service"

jwt:
  secret: "incorrect"

zuul:
  routes:
    auth-service:
      path: /auth/**
      url: http://localhost:8081
    proposal:
      sensitiveHeaders: Cookie, Set-Cookie, Authorization
      path: /proposals/**
      url: http://localhost:8082
    template:
      sensitiveHeaders: Cookie, Set-Cookie, Authorization
      path: /templates/**
      url: http://localhost:8083
