server:
  port: 8080

spring:
  application:
    name: "gateway-service"

jwt:
  secret: incorrect

zuul:
  routes:
    auth-service:
      path: /auth/**
      url: http://localhost:8081
    proposal:
      path: /proposal/**
      url: http://localhost:8082
