apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ambassador-ingress
  labels:
    app: {{ .Values.ambassador.fullnameOverride }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
        - path: /(.*)
          backend:
            serviceName: {{ .Values.ambassador.fullnameOverride }}
            servicePort: 80
            