version: '3'

services:
  template:
    image: template-image
    container_name: template-service-container
    ports:
      - 8083:8083
    build:
      context: .
      dockerfile: ./docker/template/Dockerfile
    depends_on:
      - template-mongo
  template-mongo:
    image: mongo:latest
    container_name: template-mongo-container
    restart: always
    ports:
      - 27017:27017