apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-proposal.fullname" . }}
  labels:
    {{- include "service-proposal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateType }}    
  selector:
    matchLabels:
      {{- include "service-proposal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "service-proposal.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}           
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: web
              containerPort: 8082
              protocol: TCP              
          env:
            - name: mongo.host
              valueFrom:
                configMapKeyRef:
                  name: proposal-config
                  key: MONGO_HOST  
            - name: mongo.port
              valueFrom:
                configMapKeyRef:
                  name: proposal-config
                  key: MONGO_PORT          
            - name: mongo.db
              valueFrom:
                configMapKeyRef:
                  name: proposal-config
                  key: MONGO_DB                
            - name: mongo.user
              valueFrom:
                configMapKeyRef:
                  name: proposal-config
                  key: MONGO_USER                  
            - name: mongo.password
              valueFrom:
                secretKeyRef:
                  name: proposal-secret
                  key: MONGO_PASSWORD
            - name: x_template_service_host
              value: "template-service"
            - name: x_template_service_port
              value: "9003"         
            - name: x_user_service_host
              value: "user-service"
            - name: x_user_service_port
              value: "9000"                       
          livenessProbe:
              httpGet:
                port: web
                path: /api/v1/statistic/health
              initialDelaySeconds: 60
              periodSeconds: 15
          readinessProbe:
              httpGet:
                port: web
                path: /api/v1/statistic/health
              initialDelaySeconds: 5
              periodSeconds: 3   
