apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-proposal.fullname" . }}
  labels:
    {{- include "service-proposal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: web
      protocol: TCP
      name: http
  selector:
    {{- include "service-proposal.selectorLabels" . | nindent 4 }}
