replicaCount: 1
updateType: RollingUpdate
host: arch.homework
fullnameOverride: deal-service

image: rined/dms-deal:v9

service:
  type: NodePort
  port: 9004
  
mongodb:
  fullnameOverride: mongo-deal-db
  auth:
    rootPassword: admin
    username: admin
    password: admin
    database: dms-deal
  service:
    portName: mongo-deal-db
    port: 27017

