replicaCount: 1
updateType: RollingUpdate
host: arch.homework
fullnameOverride: template-service

image: rined/dms-template:v3

service:
  type: NodePort
  port: 9003
  
mongodb:
  fullnameOverride: mongo-template-db
  auth:
    rootPassword: admin
    username: admin
    password: admin
    database: dms-template  
  service:
    portName: mongo-template-db
    port: 27017

