replicaCount: 1
updateType: RollingUpdate
host: arch.homework
fullnameOverride: auth-service

image: rined/dms-jwt-auth:v3

service:
  type: NodePort
  port: 9000

postgresql:
  fullnameOverride: pg-db
  postgresqlUsername: rined
  postgresqlPassword: password
  postgresqlDatabase: otus_app
  service:
    port: "5432"
