replicaCount: 1
updateType: RollingUpdate
host: arch.project
fullnameOverride: auth-service

image: rined/dms-jwt-auth:v3

service:
  type: NodePort
  port: 9000

postgresql:
  fullnameOverride: dms-auth-db
  postgresqlUsername: rined
  postgresqlPassword: password
  postgresqlDatabase: otus_crud_app
  service:
    port: "5432"
