replicaCount: 1
updateType: RollingUpdate
host: arch.homework
fullnameOverride: proposal-service

image: rined/dms-proposal:v16

service:
  type: NodePort
  port: 9002
  
mongodb:
  fullnameOverride: mongo-proposal-db
  auth:
    rootPassword: admin
    username: admin
    password: admin
    database: dms-proposal  
  service:
    portName: mongo-proposal-db
    port: 27017

